apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-role-binding
subjects:
- kind: ServiceAccount
  name: auth-service-account
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-service-role-binding
subjects:
- kind: ServiceAccount
  name: product-service-account
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
